--INSERT DATA
INSERT INTO SCHEDULE
(GAME_ID, GAME_DATE, OPPONENT, LOCATION, GAME_TIME, WINNER, SPREAD, HUSKER_SCORE, OPPONENT, ROW_CREATE_TSP)
VALUES
(1, 'Sat, Aug 31', 'South Alabama', 'HOME', '11:00 AM', 'TBD', 'TBD', 'TBD', 'TBD', CURRENT_TIMESTAMP),
(2, 'Sat, Sep 7', 'Colorado', 'AWAY', '2:30 PM', 'TBD', 'TBD', 'TBD', 'TBD', CURRENT_TIMESTAMP),
(3, 'Sat, Sep 14', 'Northern Illinois', 'HOME', '7:00 PM', 'TBD', 'TBD', 'TBD', 'TBD', CURRENT_TIMESTAMP),
(4, 'Sat, Sep 21', 'Illinois', 'AWAY', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', CURRENT_TIMESTAMP),
(5, 'Sat, Sep 28', 'Ohio State', 'HOME', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', CURRENT_TIMESTAMP),
(6, 'Sat, Oct 5', 'Northwestern', 'HOME', '2:30 pm', 'TBD', 'TBD', 'TBD', 'TBD', CURRENT_TIMESTAMP),
(7, 'Sat, Oct 12', 'Minnesota', 'AWAY', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', CURRENT_TIMESTAMP),
(8, 'Sat, Oct 26', 'Indiana', 'HOME', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', CURRENT_TIMESTAMP),
(9, 'Sat, Nov 2', 'Purdue', 'AWAY', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', CURRENT_TIMESTAMP),
(10, 'Sat, Nov 16', 'Wisconsin', 'HOME', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', CURRENT_TIMESTAMP),
(11, 'Sat, Nov 23', 'Maryland', 'AWAY', 'TBD', 'TBD', 'TBD', 'TBD', 'TBD', CURRENT_TIMESTAMP),
(12, 'Fri, Nov 29', 'Iowa', 'HOME', '1:30 PM', 'TBD', 'TBD', 'TBD', 'TBD', CURRENT_TIMESTAMP),

--INSERT DATA
INSERT INTO T_DC
(DC_ID, NAME, CATEGORY, GENDER, IDENTITY, ROW_CREATE_TSP)
VALUES
(1, 'BATMAN', 'HERO', 'MALE', 'SECRET', CURRENT_TIMESTAMP),
(2, 'SUPERMAN', 'HERO', 'MALE', 'SECRET', CURRENT_TIMESTAMP),
(3, 'WONDER WOMAN', 'HERO', 'FEMALE', 'PUBLIC', CURRENT_TIMESTAMP),
(4, 'TALIA AL GHUL', 'VILLAIN', 'FEMALE', 'SECRET', CURRENT_TIMESTAMP),
(5, 'CATWOMAN', 'HERO', 'FEMALE', 'SECRET', CURRENT_TIMESTAMP),
(6, 'AQUAMAN', 'HERO', 'MALE', 'PUBLIC', CURRENT_TIMESTAMP),
(7, 'LEX LUTHOR', 'VILLAIN', 'MALE', 'PUBLIC', CURRENT_TIMESTAMP),
(8, 'JOKER', 'VILLAIN', 'MALE', 'SECRET', CURRENT_TIMESTAMP),
(9, 'GREEN LANTERN', 'HERO', 'MALE', 'SECRET', CURRENT_TIMESTAMP),
(10, 'FLASH', 'HERO', 'MALE', 'SECRET', CURRENT_TIMESTAMP);